set_mode:
  description: Set the mode of the speaker.
  fields:
    entity_id:
      description: The entity_id of the KEF speaker.
      example: media_player.kef_lsx

set_desk_db:
  description: Set the "Desk mode" slider of the speaker in dB.
  fields:
    entity_id:
      description: The entity_id of the KEF speaker.
      example: media_player.kef_lsx
    db:
      description: Value of the slider (-6 to 0 with steps of 0.5)
      example: 0.0

set_wall_db:
  description: Set the "Wall mode" slider of the speaker in dB.
  fields:
    entity_id:
      description: The entity_id of the KEF speaker.
      example: media_player.kef_lsx
    db:
      description: Value of the slider (-6 to 0 with steps of 0.5)
      example: 0.0

set_treble_db:
  description: Set desk the "Treble trim" slider of the speaker in dB.
  fields:
    entity_id:
      description: The entity_id of the KEF speaker.
      example: media_player.kef_lsx
    db:
      description: Value of the slider (-2 to 2 with steps of 0.5)
      example: 0.0

set_high_hz:
  description: Set the "High-pass mode" slider of the speaker in Hz.
  fields:
    entity_id:
      description: The entity_id of the KEF speaker.
      example: media_player.kef_lsx
    hz:
      description: Value of the slider (50 to 120 with steps of 5)
      example: 95

set_low_hz:
  description: Set the "Sub out low-pass frequency" slider of the speaker in Hz.
  fields:
    entity_id:
      description: The entity_id of the KEF speaker.
      example: media_player.kef_lsx
    hz:
      description: Value of the slider (40 to 250 with steps of 5)
      example: 80

set_sub_db:
  description: Set the "Sub gain" slider of the speaker in dB.
  fields:
    entity_id:
      description: The entity_id of the KEF speaker.
      example: media_player.kef_lsx
    db:
      description: Value of the slider (-10 to 10 with steps of 1)
      example: 0
